b01project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('request_book/', include('request_book.urls')),
    path('admin/', admin.site.urls),
    path('bookmarks/', include('bookmarks.urls')),
    path('', include('pengelola.urls')),
    path('review/', include('review.urls')),
    path('booklist/', include('booklist.urls')),
    path('auth/', include('authentication.urls')),
]

booklist/urls.py
from django.urls import path
from booklist.views import show_booklist, get_book_json, get_buku_json, add_book_ajax, delete_book_ajax, delete_book_flutter, add_book_flutter

app_name = 'booklist'

urlpatterns = [
    path('', show_booklist, name='show_booklist'),
    path('get-book/', get_book_json, name='get_book_json'),
    path('get-buku/', get_buku_json, name='get_buku_json'),
    path('create-book-ajax/', add_book_ajax, name='add_book_ajax'),
    path('add-book-flutter/', add_book_flutter, name='add_book_flutter'),
    path('delete-book-ajax/', delete_book_ajax, name='delete_book_ajax'),
    path('delete-book-flutter/', delete_book_flutter, name='delete_book_flutter'),
]

bookmarks/urls.py
from django.urls import path
from bookmarks.views import add_bookmark_ajax, create_product_flutter, show_bookmarks, get_bookmark_json, delete_bookmark_ajax, show_json

app_name = 'bookmarks'

urlpatterns = [
    path('add-bookmark/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('', show_bookmarks, name='show_bookmarks'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('delete-bookmark/', delete_bookmark_ajax, name='delete_bookmark_ajax'),
    path('json/', show_json, name='show_json'), 
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

pengelola/urls.py
from django.urls import path
from pengelola.views import register , get_books, hapus_buku, tambah_buku
from pengelola.views import login_user,edit_buku, display_books, logout_user, show_main
from pengelola.views import create_buku_flutter, edit_buku_flutter, hapus_buku_flutter


app_name = 'pengelola'

urlpatterns = [
    path("", show_main, name='show_main'),
    path("register/", register, name='register'),
    path("json/", get_books, name="get_books"),
    path("hapus/<int:id>", hapus_buku, name='hapus_buku'),
    path("hapusemg/<int:id>", hapus_buku, name='hapus_buku'),
    path("tambah/", tambah_buku, name='tambah_buku'),
    path("display-books/", display_books, name="display_books"),
    path("login/", login_user, name='login'),
    path("edit/<int:id>", edit_buku, name="edit_buku"),
    path("logout/", logout_user, name="logout"),
    path("create-book/", create_buku_flutter, name="create_book"),
    path("edit-flutter/<int:id>", edit_buku_flutter, name="edit_flutter"),
    path("hapus-flutter/", hapus_buku_flutter, name="hapus_flutter"),
]

request_book/urls.py
from django.urls import path
from request_book.views import *


app_name = 'request_book'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('increase_amount/<int:product_id>/', increase_amount, name='increase_amount'),
    path('decrease_amount/<int:product_id>/', decrease_amount, name='decrease_amount'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-product-flutter/', add_product_flutter, name='add_product_flutter'),
    path('delete-product-flutter/', delete_product_flutter, name='delete_product_flutter'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete-product-ajax/<int:product_id>/', delete_product_ajax, name='delete_product_ajax'),
]

review/urls.py
from django.urls import path
from review.views import create_product_flutter
from review.views import show_json
from review.views import delete_ajax, show_ulasan, add_review_ajax, get_ulasan_json
from review.views import get_title_json

app_name = 'review'

urlpatterns = [
    path('', show_ulasan, name='show_ulasan'),
    path('get-ulasan/', get_ulasan_json, name='get_ulasan_json'),
    path('create-review-ajax/', add_review_ajax, name='add_review_ajax'),
    path('delete-ajax/', delete_ajax, name='delete_ajax'),
    path('json/', show_json, name='show_json'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    #path('book/<int:bookId>/', get_book_details, name='get_book_details'),
   path('get-title/', get_title_json, name='get_title_json'),
]

pengelola/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Buku(models.Model):
    text_number = models.IntegerField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=255 ,null=True, blank=True)
    first_name = models.CharField(max_length=255 ,null=True, blank=True)
    last_name = models.CharField(max_length=255 ,null=True, blank=True)
    year = models.CharField(max_length=255 ,null=True, blank=True)
    subjects = models.TextField(null=True, blank=True)
    bookshelves = models.TextField(null=True, blank=True, default="-")

pengelola/forms.py
from django.forms import ModelForm
from pengelola.models import Buku
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class FormBuku(ModelForm):
    class Meta:
        model = Buku
        fields = ["title","language","first_name",
                  "last_name","year","subjects", "bookshelves"]

class FormUser(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'is_staff', )

pengelola/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from pengelola.models import Buku
from pengelola.forms import FormBuku, FormUser
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.urls import reverse
import datetime
import json

@login_required(login_url='/login/')
def show_main(request):
    buku = Buku.objects.all()
    if request.user.is_staff == True:
        status = "Pustakawan"
        site = "kelola.html"
    else:
        status = "Pengguna"
        site = "main.html"

    context = {
        'username' : request.user.username,
        'status' : status,
        'buku' : buku,
        'last_login' : request.COOKIES['last_login'],
    }
    return render(request, site, context)

def get_books(request):
    data = Buku.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def display_books(request):
    data = Buku.objects.all()
    return HttpResponse(serializers.serialize("json", data))

@csrf_exempt
def register(request):
    form = FormUser()

    if request.method == "POST":
        form = FormUser(request.POST)
        print(request.POST)
        if form.is_valid():
            user = form.save()
            if user.is_staff == True:
                messages.success(request, 'Welcome new staff!')   
                return redirect('pengelola:login')
            messages.success(request, 'Your account has been successfully created!')
            return redirect('pengelola:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    next_url = request.GET.get('next', None)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if next_url:
                response = HttpResponseRedirect(next_url)
            else:
                response = HttpResponseRedirect(reverse("pengelola:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('pengelola:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
def tambah_buku(request):
    if request.method == 'POST':
        text_number = request.POST.get("text_number")
        title = request.POST.get("title")
        language = request.POST.get("language")
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        year = request.POST.get('year')
        subjects = request.POST.get('subjects')
        bookshelves = request.POST.get('bookshelves')

        new_book = Buku(text_number=text_number, title=title, language=language, first_name=first_name, 
                        last_name=last_name, year=year, subjects=subjects, bookshelves=bookshelves)
        new_book.save()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def edit_buku(request, id):
    buku = get_object_or_404(Buku, text_number = id)
    if request.method == 'POST' :
        buku.title = request.POST.get("title2")
        buku.language = request.POST.get("language2")
        buku.first_name = request.POST.get('first_name2')
        buku.last_name = request.POST.get('last_name2')
        buku.year = request.POST.get('year2')
        buku.subjects = request.POST.get('subjects2')
        buku.bookshelves = request.POST.get('bookshelves2')
        buku.save()

        return HttpResponse(b"UPDATED", status=202)
    return HttpResponseNotFound()

@csrf_exempt
def edit_buku_flutter(request, id):
    buku = get_object_or_404(Buku, pk = id)
    if request.method == 'POST' :
        data = json.loads(request.body)
        buku.text_number = int(data["text_number"])
        buku.title = data["title"]
        buku.language = data["language"]
        buku.first_name = data["first_name"]
        buku.last_name = data["last_name"]
        buku.year = data["year"]
        buku.subjects = data["subjects"]
        buku.bookshelves = data["bookshelves"]
        buku.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def hapus_buku_flutter(request):
    try:
        id = json.loads(request.body.decode('utf-8')).get('pk')
        buku = Buku.objects.filter(pk=id).get(pk=id)
        buku.delete()
        return JsonResponse({"status": "success"}, status=200)
    except:
        return JsonResponse({"status": "not found"}, status=401)

@csrf_exempt
def create_buku_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_book = Buku.objects.create(
            text_number = int(data["text_number"]),
            title = data["title"],
            language = data["language"],
            first_name = data["first_name"],
            last_name = data["last_name"],
            year = data["year"],
            subjects = data["subjects"],
            bookshelves = data["bookshelves"]
        )

        new_book.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)


@csrf_exempt
def hapus_buku(request, id):
    buku = get_object_or_404(Buku, text_number = id)
    buku.delete()
    return HttpResponse(b"DELETED", status=202)

@csrf_exempt
def emergency_hapus_buku(request, id):
    buku = get_object_or_404(Buku, pk = id)
    buku.delete()
    return HttpResponse(b"DELETED", status=202)

pengelola/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

pengelola/templates/kelola.html
{% extends 'main.html' %}

{% block side %}

<p class="mb-3">{{ status }}</p>
<p class="mb-3">{{ username }}</p>

<button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add Book
</button>

<button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#editModal">
    Edit Book
</button>

<button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#deleteModal">
    Delete Book
</button>

<a href="{% url 'bookmarks:show_bookmarks' %}">
    <button class="btn btn-secondary">
        View Bookmarks
    </button>
</a>
<a href="{% url 'booklist:show_booklist' %}">
    <button class="btn btn-secondary">
        View booklist
    </button>
</a>
<a href="{% url 'review:show_ulasan' %}">
    <button class="btn btn-secondary">
        Review
    </button>
</a>
<a href="{% url 'request_book:show_main' %}">
    <button class="btn btn-secondary">
        Book Request
    </button>
</a>

{% endblock side %}

{% block modal %}
<div class="modal fade" id="exampleModal" tabindex="0" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable overflow-auto mylimiter">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Book</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="text_number" class="col-form-label">Text Number:</label>
                        <input type="number" class="form-control" id="text_number" name="text_number"></input>
                    </div>
                    <div class="mb-3">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title" name="title"></input>
                    </div>
                    <div class="mb-3">
                        <label for="first_name" class="col-form-label">Author First Name:</label>
                        <input type="text" class="form-control" id="first_name" name="first_name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="last_name" class="col-form-label">Author Last Name:</label>
                        <input type="text" class="form-control" id="last_name" name="last_name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="year" class="col-form-label">Year:</label>
                        <input type="text" class="form-control" id="year" name="year"></input>
                    </div>
                    <div class="mb-3">
                        <label for="language" class="col-form-label">Language:</label>
                        <input type="text" class="form-control" id="language" name="language"></input>
                    </div>
                    <div class="mb-3">
                        <label for="subjects" class="col-form-label">Subjects:</label>
                        <input type="text" class="form-control" id="subjects" name="subjects"></input>
                    </div>
                    <div class="mb-3">
                        <label for="bookshelves" class="col-form-label">Type/Categories:</label>
                        <input type="text" class="form-control" id="bookshelves" name="bookshelves"></input>
                    </div>
                </form>>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Book</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="0" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable overflow-auto mylimiter">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="editModalLabel">Edit Books</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form2" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="modal-body">
                        <label for="edit_id" class="col-form-label">Insert book number(not id!):</label>
                        <input type="number" class="form-control" id="edit_id" name="edit_id"></input>
                    </div>
                    <div class="mb-3">
                        <label for="title2" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title2" name="title2"></input>
                    </div>
                    <div class="mb-3">
                        <label for="first_name2" class="col-form-label">Author First Name:</label>
                        <input type="text" class="form-control" id="first_name2" name="first_name2"></input>
                    </div>
                    <div class="mb-3">
                        <label for="last_name2" class="col-form-label">Author Last Name:</label>
                        <input type="text" class="form-control" id="last_name2" name="last_name2"></input>
                    </div>
                    <div class="mb-3">
                        <label for="year2" class="col-form-label">Year:</label>
                        <input type="text" class="form-control" id="year2" name="year2"></input>
                    </div>
                    <div class="mb-3">
                        <label for="language2" class="col-form-label">Language:</label>
                        <input type="text" class="form-control" id="language2" name="language2"></input>
                    </div>
                    <div class="mb-3">
                        <label for="subjects2" class="col-form-label">Subjects:</label>
                        <input type="text" class="form-control" id="subjects2" name="subjects2"></input>
                    </div>
                    <div class="mb-3">
                        <label for="bookshelves2" class="col-form-label">Type/Categories:</label>
                        <input type="text" class="form-control" id="bookshelves2" name="bookshelves2"></input>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_edit" data-bs-dismiss="modal">Edit Book</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" tabindex="0" id="deleteModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable overflow-auto mylimiter">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Books</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>Insert book number(not id!):</p>
            <input type="text" class="form-control" id="data_id"></input>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-warning" id="button_delete" data-bs-dismiss="modal">Delete Book</button>
        </div>
      </div>
    </div>
</div>
{% endblock modal%}

{% block funct %}
<script>
    function addBook() {
        fetch("{% url 'pengelola:tambah_buku' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshData)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addBook

    function editBook() {
        let number = document.getElementById("edit_id").value
        fetch("{% url 'pengelola:show_main' %}" + "edit/" + number, {
            method : "POST",
            body: new FormData(document.querySelector('#form2'))
        }).then(refreshData)

        document.getElementById("form2").reset()
        return false
    }
    document.getElementById("button_edit").onclick = editBook

    function deleteBook() {
        let number = document.getElementById("data_id").value
        fetch("{% url 'pengelola:show_main' %}" + "hapus/" + number, {
            method : "DELETE",
        }).then(refreshData)
        return false
    }
    document.getElementById("button_delete").onclick = deleteBook


</script>

<style>
    mylimiter{
        height: 600px;
    }
</style>
{% endblock funct %}

pengelola/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login border border-light-subtle rounded-end p-3">
    <h1>Silahkan Login Dahulu</h1>
    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>   
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
    Don't have an account yet? <a href="{% url 'pengelola:register' %}">Register Now</a>
</div>

{% endblock content %}

pengelola/templates/main.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar fixed-top mb-2 navbar-light bg-light">
    <div class="container-fluid">
        <h1 class="p-2 navbar-text flex-grow-1">Ancestral Reads</h1>
        
        <h2 class="p-2 navbar-text" style="font-size: 30px;">Selamat Datang, {{ username }}</h2>
        <a href="{% url 'pengelola:logout' %}">
            <button class="p-2 btn btn-warning">
                Logout
            </button>
        </a>
    </div>
</nav>


<nav class="sidebar mysidebar">
{% block side %}
<a href="{% url 'bookmarks:show_bookmarks' %}">
    <button class="btn btn-secondary">
        View Bookmarks
    </button>
</a>
<a href="{% url 'booklist:show_booklist' %}">
    <button class="btn btn-secondary">
        View booklist
    </button>
</a>
<a href="{% url 'review:show_ulasan' %}">
    <button class="btn btn-secondary">
        Review
    </button>
</a>
<a href="{% url 'request_book:show_main' %}">
    <button class="btn btn-secondary">
        Book Request
    </button>
</a>

{% comment %} lokasi tombol fungsi pengguna {% endcomment %}
<tr>

</tr>
<tr>

</tr>

{% endblock side %}
</nav>

<body class="mt-3" >
    <div class="mx-3" style="padding-left: 150px; padding-top: 80px;">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td>#</td>
                    <td>Title</td>
                    <td>First Name</td>
                    <td>Last Name</td>
                    <td>Year</td>
                    <td>Language</td>
                    <td>Subjects</td>
                    <td>Type/Categories</td>
                </tr>
            </thead>
            <tbody class="overflow-auto" id="table_buku" style="max-height: 400px;"></tbody>
        </table>
    </div>
</body>

{% block modal %}
{% endblock modal%}

<script>
    async function getData() {
        return fetch("{% url 'pengelola:display_books' %}").then((res) => res.json())
    }
    async function refreshData() {
        document.getElementById("table_buku").innerHTML = ""
        const Books = await getData()
        let htmlString = ``
        Books.forEach((item) => {
            htmlString += `\n<tr>
            <td>${item.fields.text_number}</td>
            <td>${item.fields.title}</td>
            <td>${item.fields.first_name}</td>
            <td>${item.fields.last_name}</td>
            <td>${item.fields.year}</td>
            <td>${item.fields.language}</td>
            <td>${item.fields.subjects}</td>
            <td>${item.fields.bookshelves}</td>
            <td><button class="btn btn-secondary" onclick="addBooks(${item.pk})" id="btn_bookmarks">Add to Bookmark</button></td>
        </tr>` 
        })
        
        document.getElementById("table_buku").innerHTML = htmlString
    }

    refreshData()

    async function addBooks(bookId) {
        const response = await fetch("{% url 'bookmarks:add_bookmark_ajax' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({ bookId: bookId })
        });

        if (response.ok) {
            alert('Book added to bookmarks');
        } else {
            alert('Failed to add book to bookmarks');
        }
    }
</script>
{% block funct %}
{% endblock funct %}

<style>
    .mysidebar{
        height: 100%;
        padding-top: 80px;
        width: 160px;
        position: fixed;
        background: #ebe7e7;
    }

    .btn {
        width: 150px;
        margin-top: 30px;
        margin-left: 5px;
        background-color: #e6e2d3;
        border-color: #e6e2d3;
        color: black;
    }

    .btn:hover {
        background-color: #96897f;
        border-color: #96897f;
    }

    #btn_bookmarks {
        background-color: #96897f;
        color: white;
    }
</style>
{% endblock content %}

pengelola/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  



<div class = "login border border-light-subtle rounded-end p-3 w-100 d-flex justify-content-between">
    
    <form method="POST" >  
        {% csrf_token %}  
        <table class="table table-borderless">
            <tr>
                <h1 class="mb-3">Register</h1>
            </tr>
            
            {{ form.as_table }}
              
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="pengguna" value="Daftar"/>
                </td>
                <td></td>  
            </tr>
             
        </table>  
    </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}