b01project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('request_book/', include('request_book.urls')),
    path('admin/', admin.site.urls),
    path('bookmarks/', include('bookmarks.urls')),
    path('', include('pengelola.urls')),
    path('review/', include('review.urls')),
    path('booklist/', include('booklist.urls')),
    path('auth/', include('authentication.urls')),
]

bookmarks/urls.py
from django.urls import path
from bookmarks.views import add_bookmark_ajax, create_product_flutter, show_bookmarks, get_bookmark_json, delete_bookmark_ajax, show_json

app_name = 'bookmarks'

urlpatterns = [
    path('add-bookmark/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('', show_bookmarks, name='show_bookmarks'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('delete-bookmark/', delete_bookmark_ajax, name='delete_bookmark_ajax'),
    path('json/', show_json, name='show_json'), 
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

pengelola/urls.py
from django.urls import path
from pengelola.views import register , get_books, hapus_buku, tambah_buku
from pengelola.views import login_user,edit_buku, display_books, logout_user, show_main
from pengelola.views import create_buku_flutter, edit_buku_flutter, hapus_buku_flutter


app_name = 'pengelola'

urlpatterns = [
    path("", show_main, name='show_main'),
    path("register/", register, name='register'),
    path("json/", get_books, name="get_books"),
    path("hapus/<int:id>", hapus_buku, name='hapus_buku'),
    path("hapusemg/<int:id>", hapus_buku, name='hapus_buku'),
    path("tambah/", tambah_buku, name='tambah_buku'),
    path("display-books/", display_books, name="display_books"),
    path("login/", login_user, name='login'),
    path("edit/<int:id>", edit_buku, name="edit_buku"),
    path("logout/", logout_user, name="logout"),
    path("create-book/", create_buku_flutter, name="create_book"),
    path("edit-flutter/<int:id>", edit_buku_flutter, name="edit_flutter"),
    path("hapus-flutter/", hapus_buku_flutter, name="hapus_flutter"),
]

review/urls.py
from django.urls import path
from review.views import create_product_flutter
from review.views import show_json
from review.views import delete_ajax, show_ulasan, add_review_ajax, get_ulasan_json
from review.views import get_title_json

app_name = 'review'

urlpatterns = [
    path('', show_ulasan, name='show_ulasan'),
    path('get-ulasan/', get_ulasan_json, name='get_ulasan_json'),
    path('create-review-ajax/', add_review_ajax, name='add_review_ajax'),
    path('delete-ajax/', delete_ajax, name='delete_ajax'),
    path('json/', show_json, name='show_json'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    #path('book/<int:bookId>/', get_book_details, name='get_book_details'),
   path('get-title/', get_title_json, name='get_title_json'),
]

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User

class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text_number = models.IntegerField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=255 ,null=True, blank=True)
    first_name = models.CharField(max_length=255 ,null=True, blank=True)
    last_name = models.CharField(max_length=255 ,null=True, blank=True)
    year = models.CharField(max_length=255 ,null=True, blank=True)
    subjects = models.TextField(null=True, blank=True)
    bookshelves = models.TextField(null=True, blank=True, default="-")
    

bookmarks/forms.py
from django.forms import ModelForm
from pengelola.models import Buku

class ProductForm(ModelForm):
    class Meta:
        model = Buku
        fields = ["title","language","first_name",
                  "last_name","year","subjects", "bookshelves"]

bookmarks/views.py
import json
from django.http import HttpResponse, HttpResponseNotFound
from django.http import HttpResponseRedirect
from bookmarks.forms import ProductForm
from django.shortcuts import redirect, render
from django.urls import reverse
from bookmarks.models import Bookmark
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from pengelola.models import Buku


# Create your views here.
def get_bookmark_json(request):
    # if request.user.is_authenticated:
    bookmark = Bookmark.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', bookmark))

@csrf_exempt
@require_POST
def add_bookmark_ajax(request):
    data = json.loads(request.body.decode('utf-8'))
    book_id = data.get('bookId')
    book = Buku.objects.get(pk=book_id)

    existing_bookmark = Bookmark.objects.filter(text_number=book.text_number, user=request.user).first()
    if existing_bookmark:
        return JsonResponse({'status': 'error', 'message': 'Book already bookmarked'}, status=400)

    bookmark = Bookmark(text_number=book.text_number, title=book.title, language=book.language, first_name=book.first_name, last_name=book.last_name, year=book.year, subjects=book.subjects, bookshelves=book.bookshelves, user=request.user)
    bookmark.save()
    
    return JsonResponse({'status': 'ok'})

@login_required(login_url='/login/')
def show_bookmarks(request):
    bookmarks = Bookmark.objects.all()
    context = {
        'bookmarks': bookmarks
    }
    return render(request, "bookmarks.html", context)

@csrf_exempt
def delete_bookmark_ajax(request):
    if request.method == "DELETE":
        try:
            data = json.loads(request.body.decode('utf-8'))
            bookmark_id = data.get('pk')
            bookmark = Bookmark.objects.get(pk=bookmark_id)
            bookmark.delete()
            return HttpResponse(b"DELETED", status=201)
        except Bookmark.DoesNotExist:
            return HttpResponse(b"Bookmark Not Found", status=404)
        except Exception as e:
            return HttpResponse(b"Error", status=500)
    return HttpResponseNotFound()

# @csrf_exempt
# def delete_bookmark_ajax(request, bookmark_id):
#    if request.method == "DELETE":
#        try:
#            bookmark = Bookmark.objects.get(pk=bookmark_id)
#            bookmark.delete()
#            return HttpResponse(b"DELETED", status=201)
#        except Bookmark.DoesNotExist:
#            return HttpResponse(b"Bookmark Not Found", status=404)
#        except Exception as e:
#            return HttpResponse(b"Error", status=500)
#    return HttpResponseNotFound()

    
def show_json(request):
    data = Bookmark.objects.all()
    return HttpResponse(serializers.serialize("json", data))

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_book = Bookmark.objects.create(
            user = request.user,
            text_number = int(data["text_number"]), 
            title = data["title"], 
            language = data["language"], 
            first_name = data["first_name"],
            last_name = data["last_name"], 
            year = data["year"], 
            subjects = data["subjects"], 
            bookshelves = data["bookshelves"]
        )

        new_book.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

bookmarks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        {% block meta %}
        {% endblock meta %}
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

bookmarks/templates/bookmarks.html
{% extends 'base.html' %}

{% block content %}
    <head>
        <!-- Add Bootstrap CSS link -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
        <!-- Optional: Add Bootstrap JavaScript and Popper.js for Bootstrap's JavaScript components -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <style>
            body {
                background-color: #c4b7a6;
            }
            nav {
                background-color: #c4b7a6;
            }

            #back-btn:hover {
                color: black;
            }

            .delete-bookmark {
                background-color: #96897f; /* Red color */
                color: white;
                border: none;
                padding: 10px 20px;
                border-radius: 8px;
                cursor: pointer;
                position: absolute;
                bottom: 10px;
                right: 10px;
            }

            /* Style for the delete button on hover */
            .delete-bookmark:hover {
                background-color: #625750; /* Darker red on hover */
            }

            .card {
                border: 1px solid #ddd;
                border-radius: 8px;
                margin: 10px;
                width: 300px;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 300px;
                overflow: hidden; 
                position: relative;
            }

            .card-body {
                text-align: left;
                padding: 15px; /* Adjust the padding as needed */
                flex-grow: 1;
                overflow-y: auto;
            }

            .card-body p {
                margin: 1px 0;
                font-size: 12px;
            }

            h6 {
                text-align: center;
            }

            .dropbtn {
            background-color: white;
            color: black;
            padding: 16px;
            font-size: 16px;
            border: none;
            cursor: pointer;
            }

            .dropdown {
            /* position: relative; */
            display: inline-block;
            }

            .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
            }

            .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            }

            .dropdown-content a:hover {background-color: #f1f1f1}

            .dropdown:hover .dropdown-content {
            display: block;
            }

            .dropdown:hover .dropbtn {
            background-color: #f1f1f1;
            }
        </style>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">
                Ancestral Reads
            </a>
            <div class="ml-auto"> <!-- Use the ml-auto class to push the "Back" button to the right -->
                <div class="dropdown">
                    <button class="dropbtn">View Bookmarks</button>
                    <div class="dropdown-content">
                        <a href="#">View Bookmarks</a>
                        <a href="#">View Booklists</a>
                        <a href="#">Book Request</a>
                    </div>
                </div>
                <a id=back-btn class="btn btn-primary" href="{% url 'pengelola:show_main' %}" style="background-color: #96897f; border:none; margin-left:30px">Back</a>
            </div>
        </nav>
    </head>
    <body>
        <div class="container mt-4">
            <br />
            <form method="POST">
                {% csrf_token %}
                <div class="row" id="bookmark-list">
                    <!-- Use a row to contain multiple cards -->
                    {% for bookmark in bookmarks %}
                        <div class="col-md-4">
                            <div class="card mb-4">
                                <h6 class="card-title">{{ bookmark.fields.title }}</h6>
                                <div class="card-body">
                                    <p class="card-text">First Name: {{ bookmark.fields.first_name }}</p>
                                    <p class="card-text">Last Name: {{ bookmark.fields.last_name }}</p>
                                    <p class="card-text">Publication Year: {{ bookmark.fields.year }}</p>
                                    <p class="card-text">Language: {{ bookmark.fields.language }}</p>
                                    <p class="card-text">Subjects: {{ bookmark.fields.subjects }}</p>
                                    <p class="card-text">Categories: {{ bookmark.fields.bookshelves }}</p>
                                </div>
                                <button class="btn btn-danger" onclick="deleteBookmark('{{ bookmark.pk }}')">Delete</button>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </form>
        </div>
    </body>
    <script>
        // Your JavaScript code here
        async function refreshBooks() {
            console.log("kerefresh")
            document.getElementById("bookmark-list").innerHTML = ""
            const bookmarks = await getBooks()
            let htmlString = ``
            bookmarks.forEach(bookmark => {
                htmlString += `
                    <div class="card mb-4">
                        <div class="card-body">
                            <h6>${bookmark.fields.title}</h6>
                            <p>First Name: ${bookmark.fields.first_name}</p>
                            <p>Last Name: ${bookmark.fields.last_name}</p>
                            <p>Publication Year: ${bookmark.fields.year}</p>
                            <p>Language: ${bookmark.fields.language}</p>
                            <p>Subjects: ${bookmark.fields.subjects}</p>
                            <p>Categories: ${bookmark.fields.bookshelves}</p>
                            <button class="delete-bookmark" onclick="deleteBookmark(${bookmark.pk})">Delete</button>
                            <br />
                        </div>
                    </div>
                `
            })
            document.getElementById("bookmark-list").innerHTML = htmlString
        }
        refreshBooks();

        async function getBooks() {
                const response = await fetch("{% url 'bookmarks:get_bookmark_json' %}");
                return response.json();
        }

        function deleteBookmark(id) {
            mydata = {pk:id}
                fetch("{% url 'bookmarks:delete_bookmark_ajax' %}", {
                    method: 'DELETE',
                    body: JSON.stringify(mydata)
                }).then(response => {
                    if (response.ok) {
                    const data = response.json();
                    console.log('Delete request successful', data);
                    refreshBooks();
                } else {
                    console.error('Delete request failed:', response.status);
                }
                });
        }
    </script>
{% endblock content %}

bookmarks/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'bookmarks:register' %}">Register Now</a>

</div>

{% endblock content %}