b01project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('request_book/', include('request_book.urls')),
    path('admin/', admin.site.urls),
    path('bookmarks/', include('bookmarks.urls')),
    path('', include('pengelola.urls')),
    path('review/', include('review.urls')),
    path('booklist/', include('booklist.urls')),
    path('auth/', include('authentication.urls')),
]

pengelola/urls.py
from django.urls import path
from pengelola.views import register , get_books, hapus_buku, tambah_buku
from pengelola.views import login_user,edit_buku, display_books, logout_user, show_main
from pengelola.views import create_buku_flutter, edit_buku_flutter, hapus_buku_flutter


app_name = 'pengelola'

urlpatterns = [
    path("", show_main, name='show_main'),
    path("register/", register, name='register'),
    path("json/", get_books, name="get_books"),
    path("hapus/<int:id>", hapus_buku, name='hapus_buku'),
    path("hapusemg/<int:id>", hapus_buku, name='hapus_buku'),
    path("tambah/", tambah_buku, name='tambah_buku'),
    path("display-books/", display_books, name="display_books"),
    path("login/", login_user, name='login'),
    path("edit/<int:id>", edit_buku, name="edit_buku"),
    path("logout/", logout_user, name="logout"),
    path("create-book/", create_buku_flutter, name="create_book"),
    path("edit-flutter/<int:id>", edit_buku_flutter, name="edit_flutter"),
    path("hapus-flutter/", hapus_buku_flutter, name="hapus_flutter"),
]

request_book/urls.py
from django.urls import path
from request_book.views import *


app_name = 'request_book'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('increase_amount/<int:product_id>/', increase_amount, name='increase_amount'),
    path('decrease_amount/<int:product_id>/', decrease_amount, name='decrease_amount'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-product-flutter/', add_product_flutter, name='add_product_flutter'),
    path('delete-product-flutter/', delete_product_flutter, name='delete_product_flutter'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete-product-ajax/<int:product_id>/', delete_product_ajax, name='delete_product_ajax'),
]

review/urls.py
from django.urls import path
from review.views import create_product_flutter
from review.views import show_json
from review.views import delete_ajax, show_ulasan, add_review_ajax, get_ulasan_json
from review.views import get_title_json

app_name = 'review'

urlpatterns = [
    path('', show_ulasan, name='show_ulasan'),
    path('get-ulasan/', get_ulasan_json, name='get_ulasan_json'),
    path('create-review-ajax/', add_review_ajax, name='add_review_ajax'),
    path('delete-ajax/', delete_ajax, name='delete_ajax'),
    path('json/', show_json, name='show_json'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    #path('book/<int:bookId>/', get_book_details, name='get_book_details'),
   path('get-title/', get_title_json, name='get_title_json'),
]

request_book/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    title = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=255, null=True, blank=True)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    year = models.IntegerField(null=True, blank=True)
    subjects = models.TextField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField()

request_book/forms.py
from django.forms import ModelForm
from request_book.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["title", "language", "first_name", "last_name", "year", "subjects"]

request_book/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from request_book.models import Product
from request_book.forms import ProductForm
import json
from django.http import *
from django.urls import reverse

from pengelola.models import Buku

from django.http import HttpResponse
from django.core import serializers

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  

from django.http import HttpResponseRedirect
from django.urls import reverse

from django.shortcuts import get_object_or_404

from django.views.decorators.csrf import csrf_exempt

def show_main(request):
    products = Product.objects.filter(user=request.user)
    books = Buku.objects.exclude(title__in=products)
    total_items = products.count()

    context = {
        'name': request.user.username,
        'class': 'PBP B',
        'products': products,
        'books': books,
        'total_items': total_items,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "request_book.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.amount = 0
        product.save()
        return HttpResponseRedirect(reverse('request_book:show_main'))

    context = {'form': form}
    return render(request, "create_req.html", context)

def increase_amount(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.amount += 1
    product.save()
    return HttpResponseRedirect(reverse('request_book:show_main'))

def decrease_amount(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    # Mengurangi jumlah barang sebanyak satu jika barang ada 
    if product.amount > 0:
        product.amount -= 1
        product.save()
        
    # Jika jumlah mencapai 0, product akan dihapus dari keranjang
    if product.amount == 0:
        product.delete()
    
    return HttpResponseRedirect(reverse('request_book:show_main'))

def delete_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    return HttpResponseRedirect(reverse('request_book:show_main'))

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('request_book:show_main'))

    context = {'form': form}
    return render(request, "edit_req.html", context)

@csrf_exempt
def add_product_ajax(request):
    print(request.POST)
    if request.method == 'POST':

        title = request.POST.get("title")
        if Buku.objects.filter(title=title).exists():
            return HttpResponse(b"DUPLICATE", status=201)

        language = request.POST.get("language")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        year = request.POST.get("year")
        subjects = request.POST.get("subjects")
        user = request.user
        amount = 0

        new_product = Product(title=title, language=language, first_name=first_name, last_name=last_name, year=year, subjects=subjects, user=user, amount=amount)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def add_product_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        title = data.get("title")
        if Buku.objects.filter(title=title).exists():
            return HttpResponse(b"DUPLICATE", status=401)
        if Product.objects.filter(title=title).exists():
            return HttpResponse(b"DUPLICATE", status=401)
        language = data.get("language")
        first_name = data.get("first_name")
        last_name = data.get("last_name")
        year = data.get("year")
        subjects = data.get("subjects")
        user = get_object_or_404(User, username=data.get('username'))
        amount = 0

        new_product = Product(title=title, language="", first_name=first_name, last_name="", year=year, subjects="", user=user, amount=amount)
        new_product.save()  

        return HttpResponse(b"CREATED", status=201)

def delete_product_flutter(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    # Mengurangi jumlah barang sebanyak satu jika barang ada 
    if product.amount > 0:
        product.amount -= 1
        product.save()
        
    # Jika jumlah mencapai 0, product akan dihapus dari keranjang
    if product.amount == 0:
        product.delete()
    
    return JsonResponse({"status": "success"}, status=200)

@csrf_exempt
def delete_product_ajax(request, id):
    if request.method == 'DELETE':
        product = get_object_or_404(Product, pk=id)
        product.delete()
        return HttpResponse(b"DELETED", status=204)
    return HttpResponseNotFound()

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

request_book/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        {% block meta %}
        {% endblock meta %}
    </head>

    <body class="base-body">
        {% block content %}
        {% endblock content %}
    </body>
</html>

request_book/templates/create_req.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header"><h1 class="text-center">Add New Book Request</h1></div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid mt-3">
                            <button class="btn btn-primary" type="submit">Add Book Request</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

request_book/templates/edit_req.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
    body {
        background-color: #c4b7a6;
    }
</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Edit Request</h1>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                        </table>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Edit Request</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

request_book/templates/request_book.html
{% extends 'base.html' %}

{% block content %}
    <style>
        body {
            background-color: #dac292;
        }
    </style>
    <style>
        table.table thead tr td:first{
            background-color: #b9936c;
            color: black;
        }
    </style>
    
    <style>
        table.table tbody tr:last-child td{
            background-color: rgb(19, 7, 73);
            color: rgb(170, 171, 179);
        }
    </style>
    

    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">AncestralReads</span>
            
        <div class="d-flex justify-content-end">
        </div>
        <a href="{% url 'pengelola:show_main' %}">
            <button type="button" class="btn btn-secondary">Back</button>                
        </a>
    </nav>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mx-auto mt-3">
                    <div class="card-body text-center">
                        <p class="card-text">Make your book request here!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
        .custom-card {
            width: 90%;
            margin: 20px auto;
        }
    </style>
    
    <div class="card custom-card">
        <div class="card-body">
            <table id="product_table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th style="white-space: nowrap; background-color:lightblue">Title</th>
                        <th style="white-space: nowrap; background-color:lightblue">Language</th>
                        <th style="white-space: nowrap; background-color:lightblue">First Name</th>
                        <th style="white-space: nowrap; background-color:lightblue">Last Name</th>
                        <th style="white-space: nowrap; background-color:lightblue">Year</th>
                        <th style="white-space: nowrap; background-color:lightblue">Subjects</th>
                    </tr>
                </thead>
            </table>
            <div id="product_cards" class="card-container">
            </div>
            <p class="text-center">Kamu menyimpan <span id="item-count">{{items}}</span> request disini<p>
            <div style="text-align: center;">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Create request by AJAX</button>
            </div>
        </div>
    </div>
    
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Request</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="title" class="col-form-label">Title:</label>
                            <input type="text" class="form-control" id="title" name="title"></input>
                        </div>
                        <div class="mb-3">
                            <label for="language" class="col-form-label">Language:</label>
                            <input type="text" class="form-control" id="language" name="language"></input>
                        </div>
                        <div class="mb-3">
                            <label for="first_name" class="col-form-label">First Name:</label>
                            <input type="text" class="form-control" id="first_name" name="first_name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="last_name" class="col-form-label">Last Name:</label>
                            <input type="text" class="form-control" id="last_name" name="last_name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="Year" class="col-form-label">Year:</label>
                            <input type="number" class="form-control" id="year" name="year"></input>
                        </div>
                        <div class="mb-3">
                            <label for="subjects" class="col-form-label">Subjects:</label>
                            <input type="text" class="form-control" id="subjects" name="subjects"></input>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Request</button>
                </div>
            </div>
        </div>
    </div>

    
    <div class="container text-center mt-3">
        <h5 style="color: black ;">Sesi terakhir login: {{ last_login }}</h5>
    </div>

    

    <script>
        async function getProducts() {
        return fetch("{% url 'request_book:get_product_json' %}").then((res) => res.json())
        }

        async function refreshProducts() {
            const products = await getProducts();
            const itemCountElement = document.getElementById("item-count");

            itemCountElement.textContent = products.length;
                let htmlString = `<table id="product_table" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Language</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Year</th>
                            <th>Subjects</th>
                        </tr>
                    </thead>
                    <tbody>`;
                        
                
            products.forEach((item) => {
                htmlString += `
                    <tr>
                        <td>${item.fields.title}</td>
                        <td>${item.fields.language}</td>
                        <td>${item.fields.first_name}</td>
                        <td>${item.fields.last_name}</td>
                        <td>${item.fields.year}</td>
                        <td>${item.fields.subjects}</td>
                        <td class="action-column">
                            <div class="btn-group" role="group">
                                <a href="edit-product/${item.pk}">
                                    <button type="submit" class="btn custom-btn3">Edit</button>
                                </a>
                                <a href="decrease_amount/${item.pk}/">
                                    <button type="submit" class="btn custom-btn2">Delete</button>
                                </a>
                            </div>
                        </td>
                    </tr>`;
            });

            htmlString += `</tbody></table>`;
            
            document.getElementById("product_table").innerHTML = htmlString;

            const cardContainer = document.getElementById("product_cards");

            cardContainer.innerHTML = "";

            products.forEach((item) => {
                // Create a card for each item
                const card = document.createElement("div");
                card.className = "product-card";

                card.innerHTML = `
                <h3>${item.fields.title}</h3>
                <p><strong>Year:</strong> ${item.fields.year}</p>
                <p><strong>Subjects:</strong> ${item.fields.subjects}</p>
                <div class="action-buttons">
                    <div class="edit-delete-buttons">
                        <a href="edit-product/${item.pk}" class="btn custom-btn3">Edit</a>
                    </div>
                    <div class="price-buttons">
                        <a href="decrease_amount/${item.pk}" class="btn custom-btn2">Delete</a>
                    </div>
                </div>
                `;

                cardContainer.appendChild(card);
            });
    }

    function deleteProduct(button, id) {
        let url = button.getAttribute('data-url').replace('123', id);
        fetch(url, {
            method: "DELETE",
        }).then(refreshProducts)
    }


    refreshProducts();


    function addProduct() {
    console.log("Function Called"); // Tambahkan ini untuk memeriksa apakah fungsi dijalankan
    fetch("{% url 'request_book:add_product_ajax' %}", {
        method: "POST",
        body: new FormData(document.querySelector('#form'))
    }).then(refreshProducts)

    document.getElementById("form").reset()
    return false
}


    document.getElementById("button_add").onclick = addProduct

    </script>

<style>
    .card-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
    }

    .product-card {
    border: 1px solid #ccc;
    padding: 10px;
    margin: 10px;
    background-color: #c6bcb6;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    border-radius: 5px;
    width: calc(33.33% - 20px);
    box-sizing: border-box;
    text-align: center;
    }

    .product-card:hover {
        transform: scale(1.05);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .product-card h3 {
    font-size: 20px;
    }

    .product-card p {
    margin: 5px 0;
    }

    .action-buttons {
    margin-top: 10px;
    }

    .custom-btn1, .custom-btn2, .custom-btn3, .custom-btn4 {
        text-decoration: none;
        padding: 5px 15px;
        margin: 5px;
        border-radius: 5px;
        color: #ffffff;
        width: 150px;
    }
    

    .custom-btn1 {
    background-color: rgb(203, 55, 55);
    }

    .custom-btn2 {
    background-color: rgb(203, 55, 55);
    }

    .custom-btn3 {
    background-color: rgb(105, 177, 59);
    color: black;
    }

    .custom-btn4 {
    background-color: red;
    }

    @media screen and (max-width: 768px) {
    .product-card {
        width: calc(50% - 20px);
    }
    }

    @media screen and (max-width: 480px) {
    .product-card {
        width: 100%;
    }
    }


</style>

{% endblock content %}