b01project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('request_book/', include('request_book.urls')),
    path('admin/', admin.site.urls),
    path('bookmarks/', include('bookmarks.urls')),
    path('', include('pengelola.urls')),
    path('review/', include('review.urls')),
    path('booklist/', include('booklist.urls')),
    path('auth/', include('authentication.urls')),
]

booklist/urls.py
from django.urls import path
from booklist.views import show_booklist, get_book_json, get_buku_json, add_book_ajax, delete_book_ajax, delete_book_flutter, add_book_flutter

app_name = 'booklist'

urlpatterns = [
    path('', show_booklist, name='show_booklist'),
    path('get-book/', get_book_json, name='get_book_json'),
    path('get-buku/', get_buku_json, name='get_buku_json'),
    path('create-book-ajax/', add_book_ajax, name='add_book_ajax'),
    path('add-book-flutter/', add_book_flutter, name='add_book_flutter'),
    path('delete-book-ajax/', delete_book_ajax, name='delete_book_ajax'),
    path('delete-book-flutter/', delete_book_flutter, name='delete_book_flutter'),
]

pengelola/urls.py
from django.urls import path
from pengelola.views import register , get_books, hapus_buku, tambah_buku
from pengelola.views import login_user,edit_buku, display_books, logout_user, show_main
from pengelola.views import create_buku_flutter, edit_buku_flutter, hapus_buku_flutter


app_name = 'pengelola'

urlpatterns = [
    path("", show_main, name='show_main'),
    path("register/", register, name='register'),
    path("json/", get_books, name="get_books"),
    path("hapus/<int:id>", hapus_buku, name='hapus_buku'),
    path("hapusemg/<int:id>", hapus_buku, name='hapus_buku'),
    path("tambah/", tambah_buku, name='tambah_buku'),
    path("display-books/", display_books, name="display_books"),
    path("login/", login_user, name='login'),
    path("edit/<int:id>", edit_buku, name="edit_buku"),
    path("logout/", logout_user, name="logout"),
    path("create-book/", create_buku_flutter, name="create_book"),
    path("edit-flutter/<int:id>", edit_buku_flutter, name="edit_flutter"),
    path("hapus-flutter/", hapus_buku_flutter, name="hapus_flutter"),
]

review/urls.py
from django.urls import path
from review.views import create_product_flutter
from review.views import show_json
from review.views import delete_ajax, show_ulasan, add_review_ajax, get_ulasan_json
from review.views import get_title_json

app_name = 'review'

urlpatterns = [
    path('', show_ulasan, name='show_ulasan'),
    path('get-ulasan/', get_ulasan_json, name='get_ulasan_json'),
    path('create-review-ajax/', add_review_ajax, name='add_review_ajax'),
    path('delete-ajax/', delete_ajax, name='delete_ajax'),
    path('json/', show_json, name='show_json'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    #path('book/<int:bookId>/', get_book_details, name='get_book_details'),
   path('get-title/', get_title_json, name='get_title_json'),
]

booklist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Book(models.Model):
    text_number = models.IntegerField(null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    language = models.CharField(max_length=255, null=True, blank=True)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    year = models.CharField(max_length=255, null=True, blank=True)
    subjects = models.TextField(null=True, blank=True)
    bookshelves = models.TextField(null=True, blank=True, default="-")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

booklist/forms.py
from django import forms
from pengelola.models import Buku
from booklist.models import Book

class addBook_form(forms.Form):
    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        super(addBook_form, self).__init__(*args, **kwargs)
        title_list = Book.objects.filter(user=request.user)
        if title_list:
            title_list = title_list.values_list('title', flat=True)
            Bukus = Buku.objects.exclude(title__in=title_list)
        else:
            Bukus = Buku.objects.all()
        field_buku = ((None, 'Select...'),)
        for book in Bukus:
            field_buku += ((book.pk, book.title),)
        self.fields['addBook_field'] = forms.ChoiceField(
            label="Options",
            widget=forms.Select(attrs={'class': 'custom-select'}),
            choices = field_buku,
        )

booklist/views.py
from django.shortcuts import render
from booklist.models import Book
from booklist.forms import addBook_form
from pengelola.models import Buku
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse

# Create your views here.

def show_booklist(request):
    title_list = Book.objects.values_list('title', flat=True)
    books = Buku.objects.exclude(title__in=title_list)
    try:
        user = request.user
    except:
        user = None

    context = {
        'nameapp': 'BookList',
        'user': user,
        'books': books,
        'form': addBook_form(request=request)
    }
    return render(request, "booklist.html", context)

def get_book_json(request):
    book_item = Book.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', book_item))

def get_buku_json(request):
    title_list = Book.objects.filter(user=request.user).values_list('title', flat=True)
    buku_item = Buku.objects.exclude(title__in=title_list)
    return HttpResponse(serializers.serialize('json', buku_item))

@csrf_exempt
def add_book_ajax(request):
    if request.method == 'POST':
        book_temp = Buku.objects.get(pk=request.POST.get("addBook_field"))
        title_list = Book.objects.filter(user=request.user).values_list('title', flat=True)
        if book_temp.title in title_list:
            return HttpResponse(b"DUPLICATE", status=201)
        new_book = Book(text_number=book_temp.text_number, title=book_temp.title, language=book_temp.language, first_name=book_temp.first_name, last_name=book_temp.last_name, year=book_temp.year, subjects=book_temp.subjects, bookshelves=book_temp.bookshelves, user=request.user)
        new_book.save()
        
        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def add_book_flutter(request):
    if request.method == 'POST':
        id = json.loads(request.body.decode('utf-8')).get('pk')
        book_temp = Buku.objects.get(pk=id)
        title_list = Book.objects.filter(user=request.user).values_list('title', flat=True)
        if book_temp.title in title_list:
            return JsonResponse({"status": "duplicate"}, status=200)
        new_book = Book(text_number=book_temp.text_number, title=book_temp.title, language=book_temp.language, first_name=book_temp.first_name, last_name=book_temp.last_name, year=book_temp.year, subjects=book_temp.subjects, bookshelves=book_temp.bookshelves, user=request.user)
        new_book.save()
        return JsonResponse({"status": "success"}, status=200)
    return JsonResponse({"status": "error"}, status=400)

@csrf_exempt
def delete_book_ajax(request):
    if request.method == "DELETE":
        try:
            id = json.loads(request.body.decode('utf-8')).get('pk')
            book_temp = Book.objects.filter(user=request.user).get(pk=id)
            book_temp.delete()
            
            return HttpResponse(b"DELETED", status=201)
        except:
            return HttpResponse(b"Not Found", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_book_flutter(request):
    if request.method == "POST":
        try:
            id = json.loads(request.body.decode('utf-8')).get('pk')
            book_temp = Book.objects.filter(user=request.user).get(pk=id, user=request.user)
            book_temp.delete()
            return JsonResponse({"status": "success"}, status=200)
        except:
            return JsonResponse({"status": "not found"}, status=200)
    return JsonResponse({"status": "error"}, status=401)

booklist/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        {% block meta %}
        {% endblock meta %}
    </head>

    <body class="base-body">
        {% block content %}
        {% endblock content %}
    </body>
</html>

booklist/templates/booklist.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/booklist.css' %}">
{% endblock meta %}

{% block content %}
    <header>
        <div class="title_header">
            <h1>{{ nameapp }}</h1>
        </div>
        <div class="btn_header">
            {% if user.is_anonymous %}
            <a href="{% url 'pengelola:login' %}?next={% url 'booklist:show_booklist' %}">
                <button type="button" class="btn btn-secondary">Login</button>                
            </a>
            <a href="{% url 'pengelola:register' %}">
                <button type="button" class="btn btn-secondary">Register</button>                
            </a>
            {% else %}
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="refreshBuku()">Tombol Add</button>
            <a href="{% url 'pengelola:show_main' %}">
                <button type="button" class="btn btn-secondary">Back</button>                
            </a>
            {% endif %}
        </div>
    </header>
    <aside>
        <div>
            <table id="book_table">
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-xl">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Book</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form id="form" onsubmit="return false;">
                                    {% csrf_token %}
                                    <div class="input-group mb-3 mx-auto justify-content-center">
                                        <div class="input-group-prepend">
                                            <label class="input-group-text" for="inputGroupSelect01">Options</label>
                                        </div>
                                        {{ form.addBook_field }}
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                            </div>
                        </div>
                    </div>
                </div>
            </table>
        </div>
    </aside>
    <footer>
        <p>Muhammad Hanif - 2206029941 - PBP B</p>
    </footer>
    <script> // For Fetch URL.
        const getBookJsonUrl = "{% url 'booklist:get_book_json' %}";
        const getBukuJsonUrl = "{% url 'booklist:get_buku_json' %}";
        const addBookJsonUrl = "{% url 'booklist:add_book_ajax' %}";
        const deleteBookJsonUrl = "{% url 'booklist:delete_book_ajax' %}";
    </script>
    <script src="{% static 'js/jsbooklist.js' %}"></script>
{% endblock content %}